-- create schema/user
drop USER adb_test_user cascade;
CREATE USER adb_test_user identified by "XXXXXXXXXXXXXXXXXXX" quota unlimited on DATA;
GRANT CONNECT, CREATE SESSION TO adb_test_user;


--drop table adb_test_user.OWNERS;
CREATE TABLE adb_test_user.OWNERS(
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL , 
    "FIRSTNAME" VARCHAR2(255) NOT NULL, 
    "LASTNAME" VARCHAR2(255) NOT NULL, 
    PRIMARY KEY ("ID")
);


--drop table adb_test_user.DOGS;
CREATE TABLE adb_test_user.DOGS(
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL, 
    "NAME" VARCHAR2(255) NOT NULL ENABLE, 
    "OWNER_ID" NUMBER(10,0) NOT NULL ENABLE, 
     PRIMARY KEY ("ID"), 
     CONSTRAINT "FK_dogs_owners" FOREIGN KEY ("OWNER_ID") REFERENCES adb_test_user.OWNERS ("ID")
);



INSERT INTO adb_test_user.owners (id, firstname, lastname) VALUES(1, 'antoine', 'masselot'), (2, 'gregoire', 'leroy'), (3, 'alex', 'mottier'), (4, 'sacha', 'ifrah');
INSERT INTO adb_test_user.dogs (name, owner_id) VALUES('toto', 1), ('gregouille', 2), ('rex', 3), ('flower', 4), ('minnie', 1), ('donald', 2);
