service:
  name: apollo

provider:
  name: scaleway
  runtime: node14

custom:
  containers:
    apollo-container:
      directory: .
      env:
        NODE_ORACLEDB_USER: BAD_USER
        NODE_ORACLEDB_PASSWORD: BAD_PASS
        NODE_ORACLEDB_CONNECTIONSTRING: BAD_DATA_SOURCE


plugins:
  - serverless-scaleway-functions

package:
  include:
    - dogs
    - demo

functions:
  demo:
    handler: demo/index.handler

  apollo-lambda:
    handler: dogs/index.handler
    env:
      NODE_ORACLEDB_USER: BAD_USER
      NODE_ORACLEDB_PASSWORD: BAD_PASS
      NODE_ORACLEDB_CONNECTIONSTRING: BAD_DATA_SOURCE
